services:
  nesto-cleanarquitecture-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Host=nesto-postgres;Port=5432;Database=nestocleanarquitecture;Username=postgres;Password=postgres;Include Error Detail=true;GSS Encryption Mode=Disable
      - ConnectionStrings__Cache=nesto-cache:6379
      - Serilog__WriteTo__1__Args__ServerUrl=http://nesto-seq:5341
      - SeedData__HostPassword=NestoHost123!
