<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Nesto.Contracts.csproj" />
    <ProjectReference Include="..\Domain\Nesto.Domain.csproj" />
    <ProjectReference Include="..\SharedKernel\Nesto.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Nesto.Application.UnitTests" />
  </ItemGroup>

</Project>
